LASTFM_API_KEY = 'YOUR_API_KEY'
LASTFM_API_SECRET = 'YOUR_API_SECRET'
LASTFM_USER = 'YOUR_LASTFM_USER'
LASTFM_MIN_PLAY_COUNT = 10
MB_RELEASE_TYPES = ['album', 'ep', 'live', 'compilation']
MB_RELEASE_STATUSES = ['official']
