# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20160111_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
