# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20160112_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='updated_albums',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
